// Generated by https://quicktype.io



export interface IChannel {
	name:					string;
	profileImg?:  string;
	userId:       string;
	subscribers:  any[];
	subscribedTo: any[];
	_id:          string;
	videos:       IVideos[];
}

export interface IVideos {
	name: 			 string;
	videoURL: 	 string;
	description: string;
	likes: 			 string[];
	dislikes: 	 string[];
}
